### ISSUE TITLE
Player will need to charge defibrillator

### ISSUE THREAD

**Issue by aovando26** [aovando26/ElectricVRJam#1]
# As the user is rubbing object together, the electricity is generated and stored in body

Draft of the action - console log by Sunday 

Object is held at a certain position - attach transform

# Canvas UI (sprite) will need to be activated to appear

**Comment by aovando26** [comment]
I was able to import assets. However, I had the following errors and warnings: 

![Image](https://github.com/aovando26/ElectricVRJam/assets/131712298/80b2c05d-ee65-4416-8a9f-1c02a85e2258)

**Comment by aovando26** [comment]
Made the necessary changes to Models - Normals are now calculate 


![Image](https://github.com/aovando26/ElectricVRJam/assets/131712298/e40af0d7-544e-4fa4-9654-7c1d10a47421)

**Comment by aovando26** [comment]
Defibrillators are now interactable with Mesh Collider and XR Grab Interactable components

**Comment by aovando26** [comment]
Made changes to game object in hierarchy instead of original prefab. Attempting to **overrides** changes to **apply all**

**Comment by aovando26** [comment]
An AudioSource and Script was added solely to the **Left Defibrillator** 
Unsure if this is most optimal implementation, but it functionality is synthesized 

![Image](https://github.com/aovando26/ElectricVRJam/assets/131712298/b29622b4-9dab-4801-a648-5de95bcf2610)

**Comment by aovando26** [comment]
I have a couple of things to add:

- A UI indicator to show the defibrillator is charging
- An animation where the defibrillators transition to a darker blue color

**Comment by syafiqoarashy** [comment]
- Finish up the "show that it's fully charged up"

**Comment by aovando26** [comment]
Defibrillator has been discarded
