### ISSUE TITLE
Door that could be opened up with certain points

### ISSUE THREAD

**Issue by aovando26** [aovando26/ElectricVRJam#11]

**Comment by aovando26** [comment]
I'm trying to create a compare tag that allows the user to use their left hand to trigger an action. However, it's currently applying to the entire XR Origin instead

One solution might be to attach a sphere (childObject) to the left hand for the trigger event. Although the direct interactable has its own collider, I haven't had success with that approach.

Additionally, in order for the door to open I set a condition that the player's score must be at least 10 


![Image](https://github.com/aovando26/ElectricVRJam/assets/131712298/0fff3ce9-d070-45b4-8301-e7ddbe930be0)

**Comment by syafiqoarashy** [comment]
I've improved the UI so that it also counts the number of souls you need to collect to open the door.

![Image](https://github.com/aovando26/ElectricVRJam/assets/101589777/0ca3e7d8-6a05-4eb3-8f55-8b8518a4e9df)
